//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Movie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public string FilmId { get; set; }
        public string URL { get; set; }
        public Nullable<int> Ep { get; set; }
        public string MovieId { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
