//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Movie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Comments = new HashSet<Comment>();
            this.Films = new HashSet<Film>();
            this.Likings = new HashSet<Liking>();
            this.Saveds = new HashSet<Saved>();
        }
    
        public string MovieId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Views { get; set; }
        public string Episodes { get; set; }
        public Nullable<System.DateTime> Years { get; set; }
        public string Description { get; set; }
        public string Thumbnails { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string CategoryId { get; set; }
        public string StudioId { get; set; }
        public string SeriesId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film> Films { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liking> Likings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saved> Saveds { get; set; }
        public virtual Studio Studio { get; set; }
        public virtual Series Series { get; set; }
    }
}
